[tool.poetry]
name = "algorithm_lib"
version = "0.1.0"
description = "The supporter who supports everyone(algorithm)."
readme = "README.md"
license = "file:LICENSE"
authors = ["shiron-dev <email@example.com>"]
repository = "https://github.com/halcyon-org/algorithm-lib"

[tool.poetry.dependencies]
python = ">=3.11"
openapi_client = { path = "./openapi_client" }

[tool.poetry.extras]
test = ["pytest"]
dev = ["black", "isort", "pytest", "mypy"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["src/test"]

[tool.mypy]
python_version = "3.11"
no_strict_optional = true
ignore_missing_imports = true
check_untyped_defs = true
