[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "algorithm_lib"
version = "0.1.0"
description = "The supporter who supports everyone(algorithm)."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.11"
authors = [{ name = "shiron-dev" }]
urls = { repository = "https://github.com/halcyon-org/algorithm-lib" }
dependencies = [
  #    "openapi_client @ ../openapi_client"
]

[project.optional-dependencies]
test = ["pytest"]
dev = ["black", "isort", "pytest", "mypy"]

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests"]
namespaces = false

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["src/test"]

[tool.mypy]
python_version = "3.11"
no_strict_optional = true
ignore_missing_imports = true
check_untyped_defs = true
