on: pull_request

jobs:
  check_python:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install poetry
        uses: abatilo/actions-poetry@v3.0.0
      - name: Install dependencies
        run: |
          poetry install
      - name: lint with black
        run: |
          poetry run black --check src
      - name: lint with isort
        run: |
          poetry run isort --check src
      - name: type check with mypy
        run: |
          poetry run mypy src
      - name: test with pytest
        run: |
          poetry run pytest
      - name: Check diff
        run: |
          if [[ `git status --porcelain` ]]; then
            exit 1
          fi
  check_openapi_client:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: openapi_client
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest
  check_openapi_gen:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.0
        with:
          version: latest
          run_install: false
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install package
        run: just setup-pnpm
      - name: just gen
        run: |
          just gen
      - name: Check diff
        run: |
          if [[ `git status --porcelain` ]]; then
            exit 1
          fi
